/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2021-12-17 08:59:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>main.jsp</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@5.14.0/css/all.min.css\">\r\n");
      out.write("    <link type=\"text/css\" href=\"/project1982/resources/css/4_main.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <!--메뉴바  ------------------------------------------------->\r\n");
      out.write("        <header class=\"header\" >\r\n");
      out.write("            <!-- 로고-->\r\n");
      out.write("               <div>\r\n");
      out.write("               <a href=\"login.do\" class=\"logo\">\r\n");
      out.write("                   <h1>1982</h1>\r\n");
      out.write("               </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <!--메뉴--> \r\n");
      out.write("             \r\n");
      out.write("               \r\n");
      out.write("               <!-- 오른쪽 메뉴-->\r\n");
      out.write("               <div class=\"right-menu\">\r\n");
      out.write("                   <!--검색 -->\r\n");
      out.write("                   <a href=\"storeClose.do\" class=\"search\">\r\n");
      out.write("                 \t  일자리찾기\r\n");
      out.write("                   </a>\r\n");
      out.write("                   <a href=\"job_positing.do\" class=\"search\">\r\n");
      out.write("                    \t구인공고\r\n");
      out.write("                   </a>\r\n");
      out.write("                   <!--유저 -->\r\n");
      out.write("                   <a href=\"userMypage.do\" class=\"user\">\r\n");
      out.write("                   \t마이페이지\r\n");
      out.write("                   </a>\r\n");
      out.write("                   <!--카트  -->\r\n");
      out.write("                   <a href=\"board.do\">\r\n");
      out.write("                  \t 고객센터\r\n");
      out.write("                       <!--카트 상품-->\r\n");
      out.write("                       \r\n");
      out.write("                   </a>\r\n");
      out.write("               </div>\r\n");
      out.write("   \r\n");
      out.write("           </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- 메인 ---------------------------------------------------------------->\r\n");
      out.write("        <main >\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"main_title\">내 주변 일자리</div>\r\n");
      out.write("                <div  class=\"main\">\r\n");
      out.write("                  <div id=\"map\" style=\"width:500px;height:450px;margin-top: 50px;border: 1px solid black;\"></div>\r\n");
      out.write("                  \r\n");
      out.write("    <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=231d9546f932fa54c056a42fd04894e8\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t\tvar mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("\t\t    mapOption = { \r\n");
      out.write("\t\t        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표\r\n");
      out.write("\t\t        level: 3 // 지도의 확대 레벨 \r\n");
      out.write("\t\t    }; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 \r\n");
      out.write("\t\tif (navigator.geolocation) {\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    // GeoLocation을 이용해서 접속 위치를 얻어옵니다\r\n");
      out.write("\t\t    navigator.geolocation.getCurrentPosition(function(position) {\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t        var  lat = position.coords.latitude, // 위도\r\n");
      out.write("\t\t             lon = position.coords.longitude; // 경도\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        var locPosition = new kakao.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다\r\n");
      out.write("\t\t            message = '<div style=\"padding:5px;\">여기에 계신가요?!</div>'; // 인포윈도우에 표시될 내용입니다\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        // 마커와 인포윈도우를 표시합니다\r\n");
      out.write("\t\t        displayMarker(locPosition, message);\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t      });\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    var locPosition = new kakao.maps.LatLng(33.450701, 126.570667),    \r\n");
      out.write("\t\t        message = 'geolocation을 사용할수 없어요..'\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t    displayMarker(locPosition, message);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 지도에 마커와 인포윈도우를 표시하는 함수입니다\r\n");
      out.write("\t\tfunction displayMarker(locPosition, message) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    // 마커를 생성합니다\r\n");
      out.write("\t\t    var marker = new kakao.maps.Marker({  \r\n");
      out.write("\t\t        map: map, \r\n");
      out.write("\t\t        position: locPosition\r\n");
      out.write("\t\t    }); \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    var iwContent = message, // 인포윈도우에 표시할 내용\r\n");
      out.write("\t\t        iwRemoveable = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    // 인포윈도우를 생성합니다\r\n");
      out.write("\t\t    var infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("\t\t        content : iwContent,\r\n");
      out.write("\t\t        removable : iwRemoveable\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    // 인포윈도우를 마커위에 표시합니다 \r\n");
      out.write("\t\t    infowindow.open(map, marker);\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    // 지도 중심좌표를 접속위치로 변경합니다\r\n");
      out.write("\t\t    map.setCenter(locPosition);      \r\n");
      out.write("}    \r\n");
      out.write("</script>\r\n");
      out.write("                  <div>  \r\n");
      out.write("                       <div class=\"main_right\"></div>\r\n");
      out.write("                       <div class=\"main_right\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                        <div class=\"main_right\"></div>\r\n");
      out.write("                        <div class=\"main_right\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"divPaging\">\r\n");
      out.write("                    <div>◀</div>\r\n");
      out.write("                       <div><b>1</b></div>\r\n");
      out.write("                    <div>2</div>\r\n");
      out.write("                    <div>3</div>\r\n");
      out.write("                    <div>4</div>\r\n");
      out.write("                    <div>5</div>\r\n");
      out.write("                    <div>▶</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"main_title\">추천 일자리</div>\r\n");
      out.write("                <div  class=\"main_article\">\r\n");
      out.write("                       <div class=\"main_right\"></div>\r\n");
      out.write("                       <div class=\"main_right\"></div>\r\n");
      out.write("                       <div class=\"main_right\"></div>\r\n");
      out.write("                        <div class=\"main_right\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"divPaging\">\r\n");
      out.write("                    <div>◀</div>\r\n");
      out.write("                       <div><b>1</b></div>\r\n");
      out.write("                    <div>2</div>\r\n");
      out.write("                    <div>3</div>\r\n");
      out.write("                    <div>4</div>\r\n");
      out.write("                    <div>5</div>\r\n");
      out.write("                    <div>▶</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer --------------------------------------------------------------------->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("            <div class=\"wrap_inner\">\r\n");
      out.write("                <div class=\"left_area\">\r\n");
      out.write("                    <h4 class=\"rap_inner_h4\">\r\n");
      out.write("                        일구하자 1982\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <div class=\"left_text\">\r\n");
      out.write("                        <div class=\"left_text_margin\">\r\n");
      out.write("                            <h5>고객센터</h5>\r\n");
      out.write("                            <p class=\"left_phone\">1566-1982</p>\r\n");
      out.write("                            <p> \r\n");
      out.write("                                <div>평일 AM 09:00 ~ PM 05:30</div>\r\n");
      out.write("                                <div>점심 PM 12:00 ~ PM 01:00</div>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"footer_icon\">\r\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-facebook-f fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\r\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-twitter fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\r\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-youtube fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\r\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-instagram fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"right_area\">\r\n");
      out.write("                    <div class=\"right_ul\">\r\n");
      out.write("                        <p>이용약관 | </p>\r\n");
      out.write("                        <p>개인정보처리방침 | </p>\r\n");
      out.write("                        <p>일구하자 이용안내 | </p>\r\n");
      out.write("                        <p>고객요청</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right_address\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <span>주식회사 1982 |</span>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("\r\n");
      out.write("                                <span>대표이사 : 한세호 |</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <span>사업자등록번호 : 123-12-12345</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <span>통신판매업신고 : 2021-서울가산-1982 |</span>\r\n");
      out.write("                            <span>WEBMASTER : 한세호</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <span>주소 : 00000 서울 금천구 벚꽃로 309 </span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <span>TEL : 1566-1982</span>\r\n");
      out.write("                            <span>E - mail : 1982@seho.co.kr</span>\r\n");
      out.write("                            <span>호스팅제공자 : 코스모(주)</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"right_copyright\">\r\n");
      out.write("                        Copyright by\r\n");
      out.write("                        <span>일구하자 1982</span>\r\n");
      out.write("                        all rights reserved.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>        \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
