/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2021-12-17 08:59:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class storeClose_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@5.14.0/css/all.min.css\">\r\n");
      out.write("    <link type=\"text/css\" href=\"/project1982/resources/css/6_my_store.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <!--메뉴바  ------------------------------------------------->\r\n");
      out.write("        <header class=\"header\" >\r\n");
      out.write("            <!-- 로고-->\r\n");
      out.write("               <div>\r\n");
      out.write("               <a href=\"login.do\" class=\"logo\">\r\n");
      out.write("                   <h1>1982</h1>\r\n");
      out.write("               </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <!--메뉴--> \r\n");
      out.write("             \r\n");
      out.write("               \r\n");
      out.write("               <!-- 오른쪽 메뉴-->\r\n");
      out.write("               <div class=\"right-menu\">\r\n");
      out.write("                   <!--검색 -->\r\n");
      out.write("                   <a href=\"storeClose.do\" class=\"search\">\r\n");
      out.write("                   일자리찾기\r\n");
      out.write("                   </a>\r\n");
      out.write("                   <a href=\"../owner/job_positing.do\" class=\"search\">\r\n");
      out.write("                    구인공고\r\n");
      out.write("                   </a>\r\n");
      out.write("                   <!--유저 -->\r\n");
      out.write("                   <a href=\"userMypage.do\" class=\"user\">\r\n");
      out.write("                   마이페이지\r\n");
      out.write("                   </a>\r\n");
      out.write("                   <!--카트  -->\r\n");
      out.write("                   <a href=\"../board.do\">\r\n");
      out.write("                   고객센터\r\n");
      out.write("                       <!--카트 상품-->\r\n");
      out.write("                       \r\n");
      out.write("                   </a>\r\n");
      out.write("               </div>\r\n");
      out.write("   \r\n");
      out.write("           </header>\r\n");
      out.write(" <!-- 메인 ---------------------------------------------------------------->\r\n");
      out.write("      <section class=\"section\">\r\n");
      out.write("          <h1>업체 검색</h1>\r\n");
      out.write("          <div class=\"select\">\r\n");
      out.write("          <select  name=\"sido1\" id=\"sido1\" >\r\n");
      out.write("              \r\n");
      out.write("          </select>\r\n");
      out.write("          <select name=\"gugun1\" id=\"gugun1\">\r\n");
      out.write("          \r\n");
      out.write("          </select>\r\n");
      out.write("          \r\n");
      out.write("        <button class=\"search_button\">검색</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("      \r\n");
      out.write("    <section class=\"section_main\">\r\n");
      out.write("           \r\n");
      out.write("      <div id=\"mainWrapper\">\r\n");
      out.write("\r\n");
      out.write("          <ul>\r\n");
      out.write("              <!-- 게시판 제목 -->\r\n");
      out.write("             \r\n");
      out.write("  \r\n");
      out.write("              <!-- 게시판 목록  -->\r\n");
      out.write("              <li>\r\n");
      out.write("                  \r\n");
      out.write("                 \r\n");
      out.write("                  <ul id =\"ulTable\">\r\n");
      out.write("                      <li>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li>업체</li>\r\n");
      out.write("                              <li>주소</li>\r\n");
      out.write("                              <li>날짜</li>\r\n");
      out.write("                              <li>시급</li>\r\n");
      out.write("                              <li>지원</li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <!-- 게시물이 출력될 영역 -->\r\n");
      out.write("                      <li>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li class=\"left\"><a href=\"#\">롯데리아</a></li>\r\n");
      out.write("                              <li class=\"left\">서울특별시 금천구 가산디지털단지</li>\r\n");
      out.write("                              <li class=\"left\">2014.07.09</li>\r\n");
      out.write("                              <li class=\"left\">8,000</li>\r\n");
      out.write("                              <li class=\"left\">\r\n");
      out.write("                                  <button class=\"button\">지원</button>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("  \r\n");
      out.write("                      <li>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li class=\"left\"><a href=\"#\">비어킹</a></li>\r\n");
      out.write("                              <li class=\"left\">제목제목제목제목1</li>\r\n");
      out.write("                              <li class=\"left\">2014.07.09</li>\r\n");
      out.write("                              <li class=\"left\">9,500</li>\r\n");
      out.write("                              <li class=\"left\">\r\n");
      out.write("                                <button class=\"button\">지원</button>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("  \r\n");
      out.write("                      <li>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li class=\"left\"><a href=\"#\">맥도날드</a></li>\r\n");
      out.write("                              <li class=\"left\">제목제목제목제목1</li>\r\n");
      out.write("                              <li class=\"left\">2014.07.09</li>\r\n");
      out.write("                              <li class=\"left\">12,000</li>\r\n");
      out.write("                              <li class=\"left\">\r\n");
      out.write("                                <button class=\"button\">지원</button>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("  \r\n");
      out.write("                      <li>\r\n");
      out.write("                          <ul>\r\n");
      out.write("                              <li class=\"left\"><a href=\"#\">비비큐</a></li>\r\n");
      out.write("                              <li class=\"left\">제목제목제목제목1</li>\r\n");
      out.write("                              <li class=\"left\">2014.07.09</li>\r\n");
      out.write("                              <li class=\"left\">19,000</li>\r\n");
      out.write("                              <li class=\"left\">\r\n");
      out.write("                                <button class=\"button\">지원</button>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      <li>                                        \r\n");
      out.write("                  </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("  \r\n");
      out.write("              <!-- 게시판 페이징 영역 -->\r\n");
      out.write("              <li>\r\n");
      out.write("                  <div id=\"divPaging\">\r\n");
      out.write("                      <div>◀</div>\r\n");
      out.write("                         <div><b>1</b></div>\r\n");
      out.write("                      <div>2</div>\r\n");
      out.write("                      <div>3</div>\r\n");
      out.write("                      <div>4</div>\r\n");
      out.write("                      <div>5</div>\r\n");
      out.write("                      <div>▶</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </li>\r\n");
      out.write("  \r\n");
      out.write("              <!-- 검색 폼 영역 -->\r\n");
      out.write("         \r\n");
      out.write("  \r\n");
      out.write("          </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <section class=\"section1\">\r\n");
      out.write("    <h1>내가 찜한 점포</h1>\r\n");
      out.write("    \r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"section_main\">\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"mainWrapper\">\r\n");
      out.write("\r\n");
      out.write("    <ul>\r\n");
      out.write("        <!-- 게시판 제목 -->\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        <!-- 게시판 목록  -->\r\n");
      out.write("        <li>\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("            <ul id =\"ulTable\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>업체</li>\r\n");
      out.write("                        <li>주소</li>\r\n");
      out.write("                        <li>날짜</li>\r\n");
      out.write("                        <li>시급</li>\r\n");
      out.write("                        <li>취소</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- 게시물이 출력될 영역 -->\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"left\"><a href=\"#\">롯데리아</a></li>\r\n");
      out.write("                        <li class=\"left\">서울특별시 서초구 반포대로</li>\r\n");
      out.write("                        <li class=\"left\">2014.07.09</li>\r\n");
      out.write("                        <li class=\"left\">8,000</li>\r\n");
      out.write("                        <li class=\"left\">\r\n");
      out.write("                            <button class=\"button\">삭제</button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"left\"><a href=\"#\">비어킹</a></li>\r\n");
      out.write("                        <li class=\"left\">제목제목제목제목1</li>\r\n");
      out.write("                        <li class=\"left\">2014.07.09</li>\r\n");
      out.write("                        <li class=\"left\">9,500</li>\r\n");
      out.write("                        <li class=\"left\">\r\n");
      out.write("                          <button class=\"button\">삭제</button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"left\"><a href=\"#\">맥도날드</a></li>\r\n");
      out.write("                        <li class=\"left\">제목제목제목제목1</li>\r\n");
      out.write("                        <li class=\"left\">2014.07.09</li>\r\n");
      out.write("                        <li class=\"left\">12,000</li>\r\n");
      out.write("                        <li class=\"left\">\r\n");
      out.write("                          <button class=\"button\">삭제</button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"left\"><a href=\"#\">비비큐</a></li>\r\n");
      out.write("                        <li class=\"left\">제목제목제목제목1</li>\r\n");
      out.write("                        <li class=\"left\">2014.07.09</li>\r\n");
      out.write("                        <li class=\"left\">19,000</li>\r\n");
      out.write("                        <li class=\"left\">\r\n");
      out.write("                          <button class=\"button\">삭제</button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                <li>                                        \r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <!-- 게시판 페이징 영역 -->\r\n");
      out.write("        <li>\r\n");
      out.write("            <div id=\"divPaging\">\r\n");
      out.write("                <div>◀</div>\r\n");
      out.write("                   <div><b>1</b></div>\r\n");
      out.write("                <div>2</div>\r\n");
      out.write("                <div>3</div>\r\n");
      out.write("                <div>4</div>\r\n");
      out.write("                <div>5</div>\r\n");
      out.write("                <div>▶</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <!-- 검색 폼 영역 -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- -------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer --------------------------------------------------------------------->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("            <div class=\"wrap_inner\">\r\n");
      out.write("                <div class=\"left_area\">\r\n");
      out.write("                    <h4 class=\"rap_inner_h4\">\r\n");
      out.write("                        일구하자 1982\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <div class=\"left_text\">\r\n");
      out.write("                        <div class=\"left_text_margin\">\r\n");
      out.write("                            <h5>고객센터</h5>\r\n");
      out.write("                            <p class=\"left_phone\">1566-1982</p>\r\n");
      out.write("                            <p> \r\n");
      out.write("                                <div>평일 AM 09:00 ~ PM 05:30</div>\r\n");
      out.write("                                <div>점심 PM 12:00 ~ PM 01:00</div>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"footer_icon\">\r\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-facebook-f fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\r\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-twitter fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\r\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-youtube fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\r\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-instagram fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"right_area\">\r\n");
      out.write("                    <div class=\"right_ul\">\r\n");
      out.write("                        <p>이용약관 | </p>\r\n");
      out.write("                        <p>개인정보처리방침 | </p>\r\n");
      out.write("                        <p>일구하자 이용안내 | </p>\r\n");
      out.write("                        <p>고객요청</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right_address\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <span>주식회사 1982 |</span>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("\r\n");
      out.write("                                <span>대표이사 : 한세호 |</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <span>사업자등록번호 : 123-12-12345</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <span>통신판매업신고 : 2021-서울가산-1982 |</span>\r\n");
      out.write("                            <span>WEBMASTER : 한세호</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <span>주소 : 00000 서울 금천구 벚꽃로 309 </span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <span>TEL : 1566-1982</span>\r\n");
      out.write("                            <span>E - mail : 1982@seho.co.kr</span>\r\n");
      out.write("                            <span>호스팅제공자 : 코스모(주)</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"right_copyright\">\r\n");
      out.write("                        Copyright by\r\n");
      out.write("                        <span>일구하자 1982</span>\r\n");
      out.write("                        all rights reserved.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>        \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("<script>\r\n");
      out.write("  $('document').ready(function() {\r\n");
      out.write(" var area0 = [\"시/도 선택\",\"서울특별시\",\"인천광역시\",\"대전광역시\",\"광주광역시\",\"대구광역시\",\"울산광역시\",\"부산광역시\",\"경기도\",\"강원도\",\"충청북도\",\"충청남도\",\"전라북도\",\"전라남도\",\"경상북도\",\"경상남도\",\"제주도\"];\r\n");
      out.write("  var area1 = [\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"];\r\n");
      out.write("   var area2 = [\"계양구\",\"남구\",\"남동구\",\"동구\",\"부평구\",\"서구\",\"연수구\",\"중구\",\"강화군\",\"옹진군\"];\r\n");
      out.write("   var area3 = [\"대덕구\",\"동구\",\"서구\",\"유성구\",\"중구\"];\r\n");
      out.write("   var area4 = [\"광산구\",\"남구\",\"동구\",     \"북구\",\"서구\"];\r\n");
      out.write("   var area5 = [\"남구\",\"달서구\",\"동구\",\"북구\",\"서구\",\"수성구\",\"중구\",\"달성군\"];\r\n");
      out.write("   var area6 = [\"남구\",\"동구\",\"북구\",\"중구\",\"울주군\"];\r\n");
      out.write("   var area7 = [\"강서구\",\"금정구\",\"남구\",\"동구\",\"동래구\",\"부산진구\",\"북구\",\"사상구\",\"사하구\",\"서구\",\"수영구\",\"연제구\",\"영도구\",\"중구\",\"해운대구\",\"기장군\"];\r\n");
      out.write("   var area8 = [\"고양시\",\"과천시\",\"광명시\",\"광주시\",\"구리시\",\"군포시\",\"김포시\",\"남양주시\",\"동두천시\",\"부천시\",\"성남시\",\"수원시\",\"시흥시\",\"안산시\",\"안성시\",\"안양시\",\"양주시\",\"오산시\",\"용인시\",\"의왕시\",\"의정부시\",\"이천시\",\"파주시\",\"평택시\",\"포천시\",\"하남시\",\"화성시\",\"가평군\",\"양평군\",\"여주군\",\"연천군\"];\r\n");
      out.write("   var area9 = [\"강릉시\",\"동해시\",\"삼척시\",\"속초시\",\"원주시\",\"춘천시\",\"태백시\",\"고성군\",\"양구군\",\"양양군\",\"영월군\",\"인제군\",\"정선군\",\"철원군\",\"평창군\",\"홍천군\",\"화천군\",\"횡성군\"];\r\n");
      out.write("   var area10 = [\"제천시\",\"청주시\",\"충주시\",\"괴산군\",\"단양군\",\"보은군\",\"영동군\",\"옥천군\",\"음성군\",\"증평군\",\"진천군\",\"청원군\"];\r\n");
      out.write("   var area11 = [\"계룡시\",\"공주시\",\"논산시\",\"보령시\",\"서산시\",\"아산시\",\"천안시\",\"금산군\",\"당진군\",\"부여군\",\"서천군\",\"연기군\",\"예산군\",\"청양군\",\"태안군\",\"홍성군\"];\r\n");
      out.write("   var area12 = [\"군산시\",\"김제시\",\"남원시\",\"익산시\",\"전주시\",\"정읍시\",\"고창군\",\"무주군\",\"부안군\",\"순창군\",\"완주군\",\"임실군\",\"장수군\",\"진안군\"];\r\n");
      out.write("   var area13 = [\"광양시\",\"나주시\",\"목포시\",\"순천시\",\"여수시\",\"강진군\",\"고흥군\",\"곡성군\",\"구례군\",\"담양군\",\"무안군\",\"보성군\",\"신안군\",\"영광군\",\"영암군\",\"완도군\",\"장성군\",\"장흥군\",\"진도군\",\"함평군\",\"해남군\",\"화순군\"];\r\n");
      out.write("   var area14 = [\"경산시\",\"경주시\",\"구미시\",\"김천시\",\"문경시\",\"상주시\",\"안동시\",\"영주시\",\"영천시\",\"포항시\",\"고령군\",\"군위군\",\"봉화군\",\"성주군\",\"영덕군\",\"영양군\",\"예천군\",\"울릉군\",\"울진군\",\"의성군\",\"청도군\",\"청송군\",\"칠곡군\"];\r\n");
      out.write("   var area15 = [\"거제시\",\"김해시\",\"마산시\",\"밀양시\",\"사천시\",\"양산시\",\"진주시\",\"진해시\",\"창원시\",\"통영시\",\"거창군\",\"고성군\",\"남해군\",\"산청군\",\"의령군\",\"창녕군\",\"하동군\",\"함안군\",\"함양군\",\"합천군\"];\r\n");
      out.write("   var area16 = [\"서귀포시\",\"제주시\",\"남제주군\",\"북제주군\"];\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" // 시/도 선택 박스 초기화\r\n");
      out.write("\r\n");
      out.write(" $(\"select[name^=sido]\").each(function() {\r\n");
      out.write("  $selsido = $(this);\r\n");
      out.write("  $.each(eval(area0), function() {\r\n");
      out.write("   $selsido.append(\"<option value='\"+this+\"'>\"+this+\"</option>\");\r\n");
      out.write("  });\r\n");
      out.write("  $selsido.next().append(\"<option value=''>구/군 선택</option>\");\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" // 시/도 선택시 구/군 설정\r\n");
      out.write("\r\n");
      out.write(" $(\"select[name^=sido]\").change(function() {\r\n");
      out.write("  var area = \"area\"+$(\"option\",$(this)).index($(\"option:selected\",$(this))); // 선택지역의 구군 Array\r\n");
      out.write("  var $gugun = $(this).next(); // 선택영역 군구 객체\r\n");
      out.write("  $(\"option\",$gugun).remove(); // 구군 초기화\r\n");
      out.write("\r\n");
      out.write("  if(area == \"area0\")\r\n");
      out.write("   $gugun.append(\"<option value=''>구/군 선택</option>\");\r\n");
      out.write("  else {\r\n");
      out.write("   $.each(eval(area), function() {\r\n");
      out.write("    $gugun.append(\"<option value='\"+this+\"'>\"+this+\"</option>\");\r\n");
      out.write("   });\r\n");
      out.write("  }\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
