/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2021-12-17 08:58:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>intro.jsp</title>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@5.14.0/css/all.min.css\">\n");
      out.write("    <link type=\"text/css\" href=\"/project1982/resources/css/1_intro.css\" rel=\"stylesheet\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("        <!--메뉴바  ------------------------------------------------->\n");
      out.write("        <header class=\"header\" >\n");
      out.write("         <!-- 로고-->\n");
      out.write("            \n");
      out.write("            <a href=\"main.do\" class=\"logo\">\n");
      out.write("                <img src=\"./3.jpg\"/>\n");
      out.write("            </a>\n");
      out.write("            \n");
      out.write("            <!--메뉴-->   \n");
      out.write("            <ul class=\"menu\">\n");
      out.write("               \n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#soge\">소개</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#team\">팀 소개</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"admin/admin_login.do\">관리자로그인</a></li>\n");
      out.write("                \n");
      out.write("            </ul>\n");
      out.write("            <!-- 오른쪽 메뉴-->\n");
      out.write("            <div class=\"right-menu\">\n");
      out.write("                <!--검색 -->\n");
      out.write("                <a href=\"#\" class=\"search\">\n");
      out.write("                    <i class=\"fas fa-search\"></i>\n");
      out.write("                </a>\n");
      out.write("                <!--유저 -->\n");
      out.write("                <a href=\"#\" class=\"user\">\n");
      out.write("                    <i class=\"far fa-user\"></i>\n");
      out.write("                </a>\n");
      out.write("                <!--카트  -->\n");
      out.write("                <a href=\"#\">\n");
      out.write("                    <i class=\"fas fa-shopping-cart\">\n");
      out.write("                    <!--카트 상품-->\n");
      out.write("                    <span class=\"num-cart-product\">0</span>\n");
      out.write("                    </i>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("    <div class=\"main\">\n");
      out.write("        <a class=\"main_button\" href=\"user/user_login.do\">구직자 로그인</a>\n");
      out.write("        <a class=\"main_button\" href=\"owner/owner_login.do\">사업자 로그인</a>\n");
      out.write("    </div>\n");
      out.write("<!-- main------------------------------------------------------------------>\n");
      out.write("    <section>\n");
      out.write("        <div class=\"title\" id=\"soge\">1982 소개</div>\n");
      out.write("        <div class=\"title_wrap\">\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">신뢰성</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">신뢰성</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">신뢰성</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"lorem\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae reiciendis molestiae inventore sint, veniam aperiam voluptatem cupiditate laborum ab, amet illo? Nostrum illum perferendis molestias placeat odit accusamus? Fugit, reprehenderit.</div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <article>\n");
      out.write("        <div class=\"title\" id=\"team\">팀 소개</div>\n");
      out.write("        <div class=\"title_wrap\">\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">한세호</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">이성대</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">송현석</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">이혁철</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">신뢰성</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">신뢰성</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">신뢰성</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">신뢰성</p>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"circle\"></div>\n");
      out.write("                <p class=\"small\">신뢰성</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </article>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- footer --------------------------------------------------------------------->\n");
      out.write("    <footer>\n");
      out.write("        <div id=\"footer\">\n");
      out.write("            <div class=\"wrap_inner\">\n");
      out.write("                <div class=\"left_area\">\n");
      out.write("                    <h4 class=\"rap_inner_h4\">\n");
      out.write("                        일구하자 1982\n");
      out.write("                    </h4>\n");
      out.write("                    <div class=\"left_text\">\n");
      out.write("                        <div class=\"left_text_margin\">\n");
      out.write("                            <h5>고객센터</h5>\n");
      out.write("                            <p class=\"left_phone\">1566-1982</p>\n");
      out.write("                            <p> \n");
      out.write("                                <div>평일 AM 09:00 ~ PM 05:30</div>\n");
      out.write("                                <div>점심 PM 12:00 ~ PM 01:00</div>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"footer_icon\">\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-facebook-f fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-twitter fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-youtube fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\n");
      out.write("                        <div><a href=\"#\"><i class=\"fab fa-instagram fa-2x\" style=\"color:rgba(0,0,0,0.5)\"></i></a></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"right_area\">\n");
      out.write("                    <div class=\"right_ul\">\n");
      out.write("                        <p>이용약관 | </p>\n");
      out.write("                        <p>개인정보처리방침 | </p>\n");
      out.write("                        <p>일구하자 이용안내 | </p>\n");
      out.write("                        <p>고객요청</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"right_address\">\n");
      out.write("                        <p>\n");
      out.write("                            <span>주식회사 1982 |</span>\n");
      out.write("                            <a href=\"#\">\n");
      out.write("\n");
      out.write("                                <span>대표이사 : 한세호 |</span>\n");
      out.write("                            </a>\n");
      out.write("                                <span>사업자등록번호 : 123-12-12345</span>\n");
      out.write("                            </p>\n");
      out.write("                        <p>\n");
      out.write("                            <span>통신판매업신고 : 2021-서울가산-1982 |</span>\n");
      out.write("                            <span>WEBMASTER : 한세호</span>\n");
      out.write("                        </p>\n");
      out.write("                        <p>\n");
      out.write("                            <span>주소 : 00000 서울 금천구 벚꽃로 309 </span>\n");
      out.write("                        </p>\n");
      out.write("                        <p>\n");
      out.write("                            <span>TEL : 1566-1982</span>\n");
      out.write("                            <span>E - mail : 1982@seho.co.kr</span>\n");
      out.write("                            <span>호스팅제공자 : 코스모(주)</span>\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <p class=\"right_copyright\">\n");
      out.write("                        Copyright by\n");
      out.write("                        <span>일구하자 1982</span>\n");
      out.write("                        all rights reserved.\n");
      out.write("                    </p>\n");
      out.write("                </div>        \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
